@extends('layouts.master')

@section('title', 'Terms & Conditions')
@section('description', 'Terms and Conditions for Autoliker Live')

@section('content')
<div style="padding-bottom:20px;">
    <div class="fb-card" style="padding:24px;margin-bottom:16px;">
        <div class="alert alert-info" style="margin-bottom:16px;">
            All games and content on this website are for <strong>entertainment purposes only</strong>. Any resemblance to real persons or events is purely coincidental.
        </div>

        <h1 style="font-size:1.4rem;font-weight:800;margin-bottom:16px;">Terms &amp; Conditions</h1>
        <p style="margin-bottom:14px;font-size:0.95rem;">By downloading or using the app, these terms will automatically apply to you – you should make sure therefore that you read them carefully before using the app. You're not allowed to copy or modify the app, any part of the app, or our trademarks in any way. You're not allowed to attempt to extract the source code of the app, and you also shouldn't try to translate the app into other languages or make derivative versions. The app itself, and all the trademarks, copyright, database rights, and other intellectual property rights related to it, still belong to tRS APPS.</p>
        <p style="margin-bottom:14px;font-size:0.95rem;">tRS APPS is committed to ensuring that the app is as useful and efficient as possible. For that reason, we reserve the right to make changes to the app or to charge for its services, at any time and for any reason. We will never charge you for the app or its services without making it very clear to you exactly what you're paying for.</p>
        <p style="margin-bottom:14px;font-size:0.95rem;">The Autoliker Live app stores and processes personal data that you have provided to us, to provide our Service. It's your responsibility to keep your phone and access to the app secure.</p>

        <hr class="fb-divider">

        <h2 style="font-size:1.1rem;font-weight:700;margin-bottom:12px;">Entertainment Purpose</h2>
        <p style="margin-bottom:14px;font-size:0.95rem;">All games, quizzes, and image generators on this platform are created solely for <strong>entertainment purposes</strong>. The results generated are random and do not reflect any actual traits, abilities, characteristics, or facts about the user. Any resemblance to real persons, living or dead, or actual events is purely coincidental.</p>

        <hr class="fb-divider">

        <h2 style="font-size:1.1rem;font-weight:700;margin-bottom:12px;">Changes to This Terms and Conditions</h2>
        <p style="margin-bottom:14px;font-size:0.95rem;">I may update our Terms and Conditions from time to time. Thus, you are advised to review this page periodically for any changes. I will notify you of any changes by posting the new Terms and Conditions on this page.</p>
        <p style="margin-bottom:14px;font-size:0.95rem;">These terms and conditions are effective as of 2022-10-13</p>

        <hr class="fb-divider">

        <h2 style="font-size:1.1rem;font-weight:700;margin-bottom:12px;">Contact Us</h2>
        <p style="margin-bottom:14px;font-size:0.95rem;">If you have any questions or suggestions about our Terms and Conditions, do not hesitate to contact us at support@autolikerlive.com.</p>
        <p style="margin-bottom:14px;font-size:0.95rem;">This Terms and Conditions page was generated by <a href="https://app-privacy-policy-generator.nisrulz.com/" target="_blank" rel="noopener noreferrer">App Privacy Policy Generator</a>.</p>
    </div>

    <div class="text-center text-sm text-secondary">
        All games and content are for <strong>entertainment purposes only</strong>.<br>
        &copy; {{ date('Y') }} Autoliker Live. All rights reserved.
    </div>
</div>
@stop